# Generated by Django 2.2.6 on 2020-02-21 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('J_title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('J_text', models.TextField(null=True, verbose_name='任务要求')),
                ('J_files', models.FileField(null=True, upload_to='TeacherJobs', verbose_name='任务附件')),
                ('J_images', models.ImageField(null=True, upload_to='TeacherJobs', verbose_name='任务图片')),
                ('J_count', models.IntegerField(verbose_name='完成人数')),
                ('J_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('J_U', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TeacherJobs',
            },
        ),
        migrations.CreateModel(
            name='StudentJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_files', models.FileField(null=True, upload_to='StudentJobs', verbose_name='提交的任务')),
                ('S_is', models.BooleanField(verbose_name='是否通过')),
                ('S_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('S_J', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.TeacherJobs')),
                ('S_U', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'StudentJobs',
            },
        ),
    ]
