# Generated by Django 2.2.6 on 2020-02-21 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0002_auto_20200221_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherjobs',
            name='T_files',
        ),
        migrations.RemoveField(
            model_name='teacherjobs',
            name='T_images',
        ),
        migrations.CreateModel(
            name='JobFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('J_files', models.FileField(null=True, upload_to='TeacherJobs', verbose_name='任务附件')),
                ('J_T', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.TeacherJobs')),
            ],
            options={
                'db_table': 'JobFiles',
            },
        ),
        migrations.CreateModel(
            name='FilesShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_files', models.FileField(null=True, upload_to='FilesShare', verbose_name='文件共享')),
                ('F_U', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FilesShare',
            },
        ),
    ]
