# Generated by Django 2.2.6 on 2020-02-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200221_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesshare',
            name='F_name',
            field=models.CharField(default='', max_length=200, verbose_name='文件名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobfiles',
            name='J_name',
            field=models.CharField(default='', max_length=200, verbose_name='文件名'),
            preserve_default=False,
        ),
    ]
