# Generated by Django 2.2.6 on 2020-02-22 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0004_auto_20200222_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesshare',
            name='F_time',
            field=models.DateTimeField(auto_now_add=True, default='2020-02-22 21:37:20', verbose_name='上传时间'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='filesshare',
            table='File_FilesShare',
        ),
        migrations.AlterModelTable(
            name='jobfiles',
            table='File_JobFiles',
        ),
        migrations.AlterModelTable(
            name='studentjobs',
            table='File_StudentJobs',
        ),
        migrations.AlterModelTable(
            name='teacherjobs',
            table='File_TeacherJobs',
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_log', models.CharField(max_length=300)),
                ('D_time', models.DateTimeField(auto_now_add=True, verbose_name='下载时间')),
                ('D_U', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_DownloadLog',
            },
        ),
    ]
