# Generated by Django 2.2.6 on 2020-02-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20200222_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentjobs',
            name='S_name',
            field=models.CharField(default='', max_length=200, verbose_name='文件名'),
            preserve_default=False,
        ),
    ]
