# Generated by Django 2.2.6 on 2020-02-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_studentjobs_s_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentjobs',
            name='S_is',
            field=models.BooleanField(default=None, verbose_name='是否通过'),
        ),
    ]
