# Generated by Django 2.2.6 on 2020-02-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20200223_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentjobs',
            name='S_num',
            field=models.FloatField(null=True, verbose_name='分数'),
        ),
    ]
