# Generated by Django 2.2.6 on 2020-02-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='男', max_length=5),
            preserve_default=False,
        ),
    ]
