# Generated by Django 2.2.6 on 2020-02-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200204_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_rank',
            field=models.CharField(default=None, max_length=20, verbose_name='身份'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=5, verbose_name='性别'),
        ),
    ]
