# Generated by Django 2.2.6 on 2020-02-20 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200213_1201'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='U_user',
        ),
    ]
