# Generated by Django 2.2.6 on 2020-02-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200220_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='del_log',
            field=models.IntegerField(default=0, verbose_name='删除记录'),
        ),
    ]
