# Generated by Django 2.2.6 on 2020-02-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_del_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_rank',
            field=models.CharField(max_length=20, null=True, verbose_name='身份'),
        ),
    ]
